use std::collections::HashMap;

pub fn get_acronyms() -> HashMap<&'static str, &'static str> {
    let mut acronyms = HashMap::new();
    acronyms.insert("API", "Application Programming Interface");
    acronyms.insert("HTTP", "Hypertext Transfer Protocol");
    acronyms.insert("SSL", "Secure Sockets Layer");
    acronyms.insert("VPN", "Virtual Private Network");
    acronyms.insert("DDoS", "Distributed Denial of Service");
    acronyms.insert("2FA", "2-factor Authentication");
    acronyms.insert("AAA", "Authentication, Authorization, and Accounting");
    acronyms.insert("ABAC", "Attribute Based Access Control");
    acronyms.insert("ABI", "Application Binary Interface");
    acronyms.insert("ACE", "AccessData Certified Examiner");
    acronyms.insert("ACE", "Access Control Entry");
    acronyms.insert("ACE", "Arbitrary Code Execution");
    acronyms.insert("ACL", "Access Control Lists");
    acronyms.insert("ADB", "Android Debug Bridge");
    acronyms.insert("ADFS", "Active Directory Federation Services");
    acronyms.insert("AD", "Active Directory");
    acronyms.insert("AES", "Advanced Encryption Standard");
    acronyms.insert("AFAIK", "As Far As I Know");
    acronyms.insert("AFK", "Away from Keyboard");
    acronyms.insert("AI", "Artificial Intelligence");
    acronyms.insert("AJAX", "Asynchronous JavaScript And XML");
    acronyms.insert("ALE", "Annualized Loss Expectancy");
    acronyms.insert("AMS", "Asset Management System");
    acronyms.insert("ANSI", "American National Standards Institute");
    acronyms.insert("API", "Application Programming Interface");
    acronyms.insert("APK", "Android Package");
    acronyms.insert("APT", "Advanced Persistent Threat");
    acronyms.insert("APT", "Application Penetration Testing");
    acronyms.insert("AP", "Access Point");
    acronyms.insert("ARO", "Annualised Rate of Occurrence");
    acronyms.insert("ASCII", "American Standard Code for Information Interchange");
    acronyms.insert("ASLR", "Address Space Layout Randomization");
    acronyms.insert("ASN", "Autonomous System Number");
    acronyms.insert("ASV", "Approved Scanning Vendors");
    acronyms.insert("AS", "Application Server");
    acronyms.insert("AS", "Autonomous System (networking)");
    acronyms.insert("ATM", "At the moment");
    acronyms.insert("ATM", "Automated Teller Machine");
    acronyms.insert("ATP", "Advanced Threat Protection (Microsoft Defender)");
    acronyms.insert("AUP", "Acceptable Use Policy");
    acronyms.insert("AV", "Antivirus");
    acronyms.insert("AV", "Asset Value");
    acronyms.insert("AWS", "Amazon Web Services");
    acronyms.insert("AXFR", "Authoritative Zone Transfer (DNS)");
    acronyms.insert("BAU", "Business As Usual");
    acronyms.insert("BBS", "Bulletin Board System");
    acronyms.insert("BCC", "Blind Carbon Copy");
    acronyms.insert("BCRs", "Binding Corporate Rules (for intra group data transfers)");
    acronyms.insert("BER", "Bit Error Rate");
    acronyms.insert("BGP", "Border Gateway Protocol");
    acronyms.insert("BIA", "Burned-in Address");
    acronyms.insert("BIA", "Business Impact Analysis");
    acronyms.insert("BLOB", "Binary Large Object");
    acronyms.insert("BMP", "Bitmap Image format");
    acronyms.insert("BoF", "Buffer Overflow");
    acronyms.insert("BPDU", "Bridge Protocol Data Unit");
    acronyms.insert("BSD", "Berkeley Software Distribution (UNIX)");
    acronyms.insert("BSOD", "Blue Screen of Death (Windows crash)");
    acronyms.insert("BSSID", "Basic Service Set Identifier");
    acronyms.insert("BSS", "Block Started by Symbol");
    acronyms.insert("BTW", "By the way");
    acronyms.insert("BYOD", "Bring Your Own Device");
    acronyms.insert("C2", "Command and Control");
    acronyms.insert("CACE", "Excida IEC 62443 Certified Automation Cybersecurity Expert");
    acronyms.insert("CACS", "Excida IEC 62443 Certified Automation Cybersecurity Specialist");
    acronyms.insert("CAMS", "IMI Certfied Access Management Specialist");
    acronyms.insert("CAM", "Computer-aided Manufacturing");
    acronyms.insert("CAPTCHA", "Completely Automated Public Turing test to tell Computers and Humans Apart");
    acronyms.insert("CAP", "(ISC)2 Certified Authorization Professional");
    acronyms.insert("CASE", "EC Council Certified Application Security Engineer (.NET or Java)");
    acronyms.insert("CASM", "GAQM Certified Agile Scrum Master");
    acronyms.insert("CASST", "GAQM Certified Advanced Software Security Tester");
    acronyms.insert("CAWFE", "IACIS Certified Advanced Windows Forensic Examiner");
    acronyms.insert("CA", "Certification Authority");
    acronyms.insert("CBC", "Cipher Block Chaining");
    acronyms.insert("CBSP", "Cloud-based Security Providers");
    acronyms.insert("CCAr", "Cisco Certified Architect");
    acronyms.insert("CCDE", "Cisco Certified Design Expert");
    acronyms.insert("CCE", "ISFCE Certified Computer Examiner");
    acronyms.insert("CCFE", "IACRB Certified Computer Forensics Examiner");
    acronyms.insert("CCIE Ent", "Cisco Certified Internetwork Expert - Enterprise Infrastructure");
    acronyms.insert("CCISO", "EC Council Certified Information Security Officer");
    acronyms.insert("CCNA", "Cisco Certified Network Associate");
    acronyms.insert("CCNP Ent", "Cisco Certified Network Professional - Enterprise");
    acronyms.insert("CCNP Sec", "Cisco Certified Network Professional - Security");
    acronyms.insert("CCPA", "California’s Consumer Privacy Act");
    acronyms.insert("CCRMP", "IBITGQ Certified in Managing Cyber Security Risk");
    acronyms.insert("CCSA", "Checkpoint Certified Security Administrator");
    acronyms.insert("CCSC", "CertNexus Cyber Secure Coder");
    acronyms.insert("CCSE", "Checkpoint Certified Security Expert");
    acronyms.insert("CCSM", "Checkpoint Certified Security Master");
    acronyms.insert("CCSP", "(ISC)2 Certified Cloud Security Professional");
    acronyms.insert("CCTHP", "IACRB Certified Cyber Threat Hunting Professional");
    acronyms.insert("CCTV", "Closed Circuit Television");
    acronyms.insert("CCT", "Cisco Certified Technician");
    acronyms.insert("CC", "Carbon Copy");
    acronyms.insert("CC", "Credit Cards (Carding fraud)");
    acronyms.insert("CDE", "Cardholder Data Environment (network segment containing credit cards)");
    acronyms.insert("CDMA", "Code Division Multiple Access");
    acronyms.insert("CDN", "Content Delivery Network");
    acronyms.insert("CDPSE", "ISACA Certified Data Privacy Solutions Engineer");
    acronyms.insert("CDP", "Cisco Discovery Protocol");
    acronyms.insert("CDP", "Clean Desk Policy");
    acronyms.insert("CDP", "IMI Certified in Data Protection");
    acronyms.insert("CDRP", "IACRB Certified Data Recovery Professional");
    acronyms.insert("CECS", "Lunarline Certified Expert in Cloud Security");
    acronyms.insert("CEH", "EC Council Certified Ethical Hacker");
    acronyms.insert("CEIA", "Lunarline Certified Expert Independent Assessor");
    acronyms.insert("CEIM", "Lunarline Certified Expert Incident Manager");
    acronyms.insert("CEO", "Chief Executive Officer");
    acronyms.insert("CEPM", "Lunarline Certified Expert Program Manager");
    acronyms.insert("CEPP", "Lunarline Certified Expert Privacy Professional");
    acronyms.insert("CEPT", "IACRB Certified Expert Penetration Tester");
    acronyms.insert("CEREA", "IACRB Certified Expert Reserve Engineering Analyst");
    acronyms.insert("CERP", "Lunarline Certified Expert RMF Professional");
    acronyms.insert("CESA", "Lunarline Certified Expert Security Analyst");
    acronyms.insert("CESE", "Lunarline Certified Expert Security Executive");
    acronyms.insert("CESO", "Lunarline Certified Expert Security Officer");
    acronyms.insert("CFAA", "Computer Fraud and Abuse Act");
    acronyms.insert("CFA", "GAQM Certified Forensic Analyst");
    acronyms.insert("CFCE", "IACIS Certified Forensic Computer Examiner");
    acronyms.insert("CFO", "Chief Financial Officer");
    acronyms.insert("CFR", "CertNexus CyberSec First Responder");
    acronyms.insert("CFSR", "OpenText Certified Forensic Security Responder");
    acronyms.insert("CGEIT", "ISACA Certified in the Governance of Enterprise IT");
    acronyms.insert("CGI", "Common Gateway Interface");
    acronyms.insert("CHAT", "ISECOM Certified Hacker Analyst Trainer");
    acronyms.insert("CHA", "ISECOM Certified Hacker Analyst");
    acronyms.insert("CHFI", "EC Council Computer Hacking Forensics Investigator");
    acronyms.insert("CIAM", "Identify Management Institute Certified Identify and Access Manager");
    acronyms.insert("CIA", "Confidentiality, Integrity, Availability");
    acronyms.insert("CIC", "Cyber Intelligence Center");
    acronyms.insert("CIDR", "Classless Inter-Domain Routing");
    acronyms.insert("CIFS", "Common Internet File System");
    acronyms.insert("CIGE", "IMI Certified Identity Governance Expert");
    acronyms.insert("CIISec ICSF", "CIISec Information and Cybersecurity Fundamentals");
    acronyms.insert("CIISec", "Chartered Institute of Information Security");
    acronyms.insert("CIMP", "IMI Certified Identity Management Professional");
    acronyms.insert("CIOTSP", "CertNexus Certified Internet of Things Security Practitioner");
    acronyms.insert("CIO", "Chief Information Officer");
    acronyms.insert("CIPA", "IMI Certified Identity Protection comptia-advanced-security-practitioner");
    acronyms.insert("CIPP", "IAPP Certified Information Privacy Professional");
    acronyms.insert("CIPT", "IAPP Certified Information Privacy Technologist");
    acronyms.insert("CIRM Fdn", "IBITGQ Cyber Incident Response Management Foundation");
    acronyms.insert("CIRT", "Computer Incident Response Team");
    acronyms.insert("CISA", "ISACA Certified Information Systems Auditor");
    acronyms.insert("CISM", "ISACA Certified Information Security Manager");
    acronyms.insert("CISO", "Chief Information Security Officer");
    acronyms.insert("CISP", "GAQM Certified Information Security Professional");
    acronyms.insert("CISRM", "IBITGQ Certified ISO 27005 Information Security Management Specialist Risk Management");
    acronyms.insert("CISSM", "GAQM Certified Information Systems Security Manager");
    acronyms.insert("CISSP", "(ISC)2 Certified Information Systems Security Professional");
    acronyms.insert("CISST", "GAQM Certified Information Systems Security Tester");
    acronyms.insert("CIST", "IMI Certified Identity and Security Technologist");
    acronyms.insert("CIS F", "IBITGQ Certified ISO 27001 Information Security Management Specialist Foundation");
    acronyms.insert("CIS IA", "IBITGQ Certified ISO 27001 Information Security Management Specialist Internal Auditor");
    acronyms.insert("CIS LA", "IBITGQ Certified ISO 27001 Information Security Management Specialist Lead Auditor");
    acronyms.insert("CIS LI", "IBITGQ Certified ISO 27001 Information Security Management Specialist Lead Implementer");
    acronyms.insert("CIS RM", "IBITGQ Certified ISO 27005 Information Security Management Specialist Risk Management");
    acronyms.insert("CIS", "Center for Internet Security");
    acronyms.insert("CITGP", "IBITGQ Certified in Implementing IT Governance - Foundation & Principles");
    acronyms.insert("CI/CD", "Continuous Integration and either Continuous Delivery or Continuous Deployment");
    acronyms.insert("CI", "Critical Infrastructure");
    acronyms.insert("CLI", "Command-line Interface");
    acronyms.insert("CMDB", "Configuration Management Database");
    acronyms.insert("CMDB", "Content Management Database");
    acronyms.insert("CMFE", "IACRB Certified Mobile Forensics Examiner");
    acronyms.insert("CMO", "Chief Marketing Officer");
    acronyms.insert("CMS", "Content Management System");
    acronyms.insert("CMWAPT", "IACRB Certified Mobile and Web App Penetration Tester");
    acronyms.insert("CNA", "Certification and Accreditation");
    acronyms.insert("CNDA", "EC Council Certified Network Defense Architect");
    acronyms.insert("CND", "EC Council Certified Network Defender");
    acronyms.insert("COO", "Chief Operating Officer");
    acronyms.insert("CORS", "Cross-Origin Resource Sharing");
    acronyms.insert("CPC", "Core Protection System");
    acronyms.insert("CPD", "GAQM Certified Project Director");
    acronyms.insert("CPE", "Common Platform Enumeration");
    acronyms.insert("CPT", "IACRB Certified Penetration Tester");
    acronyms.insert("CRC", "Cyclical Redundancy Check");
    acronyms.insert("CREA", "IACRB Certified Reverse Engineering Analyst");
    acronyms.insert("CREST CCSAS", "CREST Certified Simulated Attack Specialist");
    acronyms.insert("CREST CCT", "CREST Certified Infrastructure Tester");
    acronyms.insert("CREST CHIA", "CREST Certified Host Intrusion Analyst");
    acronyms.insert("CREST CMRE", "CREST Certified Malware Reverse Engineer");
    acronyms.insert("CREST CNIA", "CREST Certified Network Intrusion Analyst");
    acronyms.insert("CREST CPIA", "CREST Practitioner Intrusion Analyst");
    acronyms.insert("CREST CPSA", "CREST Practitioner Security Analyst");
    acronyms.insert("CREST CPTIA", "CREST Practitioner Threat Intelligence Analyst");
    acronyms.insert("CREST CRIA", "CREST Registered Intrusion Analyst");
    acronyms.insert("CREST CRTSA", "CREST Registered Technical Security Architect");
    acronyms.insert("CREST CRT", "CREST Registered Penetration Tester");
    acronyms.insert("CREST CSAM", "CREST Certified Simulated Attack Manager");
    acronyms.insert("CREST CSAS", "CREST Certified Simulated Attack Specialist");
    acronyms.insert("CREST CTIM", "CREST Certified Threat Intelligence Manager");
    acronyms.insert("CREST CWAT", "CREST Certified Web Application Tester");
    acronyms.insert("CREST CWS", "CREST Certified Wireless Specialist");
    acronyms.insert("CREST RTIA", "CREST Registered Threat Intelligence Analyst");
    acronyms.insert("CREST", "Council for Registered Ethical Security Testers");
    acronyms.insert("CRFS", "IMI Certified Red Flag Specialist");
    acronyms.insert("CRISC", "ISACA Certified in Risk and Information Systems Control");
    acronyms.insert("CRM", "Customer Relations Management");
    acronyms.insert("CRO", "Chief Revenue Officer");
    acronyms.insert("CRTOP", "IACRB Certified Red Team Operations Professional");
    acronyms.insert("CRUD", "Create, Read, Update, Destroy");
    acronyms.insert("CSAE", "Cyber Struggle AEGIS");
    acronyms.insert("CSAP", "IACRB Certified Security Awareness Practitioner");
    acronyms.insert("CSA CCSK", "Cloud Security Alliance Certificate of Cloud Security Knowledge");
    acronyms.insert("CSA CGC", "Cloud Security Alliance Cloud Governance & Compliance");
    acronyms.insert("CSA", "Consultant Service Agreement");
    acronyms.insert("CSA", "EC Council Certified SOC Analyst");
    acronyms.insert("CSBA", "QAI Certified Software Business Analyst");
    acronyms.insert("CSCU", "EC Council Certified Secure Computer User");
    acronyms.insert("CSFA", "CSIAC CyberSecurity Forensic Analyst");
    acronyms.insert("CSIRT", "Computer Security Incident Response Team");
    acronyms.insert("CSMA/CD", "Carrier Sense Multiple Access with Collision Detection");
    acronyms.insert("CSM", "GAQM Certified Scrum Master");
    acronyms.insert("CSPRNG", "Cryptographically Secure Pseudo-Random Number Generator");
    acronyms.insert("CSP", "Content Security Policy");
    acronyms.insert("CSP", "GAQM Certified SAFe Practitioner");
    acronyms.insert("CSRF", "Cross-Site Request Forgery");
    acronyms.insert("CSR", "Cyber Struggle Ranger");
    acronyms.insert("CSSA", "IACRB Certified SCADA Security Architect");
    acronyms.insert("CSSLP", "(ISC)2 Certified Secure Software Lifecycle Professional");
    acronyms.insert("CSST", "GAQM Certified Software Security Tester");
    acronyms.insert("CSS", "Cascading Style Sheets");
    acronyms.insert("CSV", "Comma-separated Values");
    acronyms.insert("CSWSH", "Cross-Site WebSocket Hijacking");
    acronyms.insert("CSX-F", "IBITGQ Cyber Incident Response Management Foundation");
    acronyms.insert("CSX-PA", "ISACA Cybersecurity Packet Analysis Certificate");
    acronyms.insert("CSX-P", "ISACA Cybersecurity Practitioner");
    acronyms.insert("CSX-T", "ISACA Cybersecurity Technical Foundation");
    acronyms.insert("CTF", "Capture the Flag");
    acronyms.insert("CTIA", "EC Council Certified Threat Intelligence Analyst");
    acronyms.insert("CTI", "Cyber Threat Intelligence");
    acronyms.insert("CTOps", "Cyber Threat Operations");
    acronyms.insert("CTO", "Chief Technology Officer");
    acronyms.insert("CTR", "Click-through Rate");
    acronyms.insert("CUCM", "Cisco Unified Communications Manager");
    acronyms.insert("CVE", "Common Vulnerabilities and Exposures");
    acronyms.insert("CVSS", "Common Vulnerability Scoring System");
    acronyms.insert("CWE", "Common Weakness Enumeration");
    acronyms.insert("CW", "Content Warning");
    acronyms.insert("CySA+", "CompTIA Cybersecurity Analyst+");
    acronyms.insert("C CS F", "IBITGQ Certified Cyber Security Foundation");
    acronyms.insert("C&A", "Certification and Accreditation");
    acronyms.insert("C&C", "Command and Control");
    acronyms.insert("C)CSO", "Mile2 Certified Cloud Security Officer");
    acronyms.insert("C)DFE", "Mile2 Certified Digital Forensics Examiner");
    acronyms.insert("C)ISCAP", "Mile2 Information Systems Certification and Accreditation Professional");
    acronyms.insert("C)ISMS-LA", "Mile2 Certified Information Security Management Systems Lead Auditor");
    acronyms.insert("C)ISSA", "Mile2 Certified Information Systems Security Auditor");
    acronyms.insert("C)ISSM", "Mile2 Certified Information Systems Security Manager");
    acronyms.insert("C)ISSO", "Mile2 Certified Information Systems Security Officer");
    acronyms.insert("C)NFE", "Mile2 Certified Network Forensics Examiner");
    acronyms.insert("C)PEH", "Mile2 Certified Professional Ethical Hacker");
    acronyms.insert("C)PSH", "Mile2 Certified Powershell Hacker");
    acronyms.insert("C)PTC", "Mile2 Certified Penetration Testing Expert");
    acronyms.insert("C)PTE", "Mile2 Certified Penetration Testing Engineer");
    acronyms.insert("C)SLO", "Mile2 Certified Security Leadership Officer");
    acronyms.insert("C)SP", "Mile2 Certified Security Principles");
    acronyms.insert("C)VA", "Mile2 Certified Vulnerability Assessor");
    acronyms.insert("C)VCP", "Mile2 Certified Virtualization & Cloud Principles");
    acronyms.insert("C)VE", "Mile2 Certified Virtualization Engineer");
    acronyms.insert("C)VFE", "Mile2 Certified Virtualization Forensics Examiner");
    acronyms.insert("DACL", "Discretionary Access Control List");
    acronyms.insert("DACRP", "DRI Associate Cyber Resilience Professional");
    acronyms.insert("DAO", "Direct Access Object");
    acronyms.insert("DAST", "Dynamic Application Security Testing");
    acronyms.insert("DBA", "Database Administrator");
    acronyms.insert("DCBCA", "DRI Certified Business Continuity Auditor");
    acronyms.insert("DCBCLA", "DRI Certified Business Continuity Lead Auditor");
    acronyms.insert("DCCRP", "DRI Certified Cyber Resilience Professional");
    acronyms.insert("DCOM", "Distributed Component Object Model");
    acronyms.insert("DCPP", "DSCI Certified Privacy Professional");
    acronyms.insert("DCRMP", "DRI Certified Risk Management Professional");
    acronyms.insert("DCSA", "Defense Counterintelligence and Security Agency");
    acronyms.insert("DCS", "Data Communication Systems");
    acronyms.insert("DCS", "Distributed Control System");
    acronyms.insert("DC", "Data Center");
    acronyms.insert("DC", "Domain Controller (Active Directory)");
    acronyms.insert("DDE", "Dynamic Data Exchange");
    acronyms.insert("DDoS", "Distributed Denial of Service");
    acronyms.insert("DES", "Data Encryption Standard");
    acronyms.insert("DevNet A", "Cisco DevNet Associate");
    acronyms.insert("DevNet Pro", "Cisco DevNet Professional");
    acronyms.insert("DFIR", "Digital Forensics Incident Response");
    acronyms.insert("DH", "Diffie-Hellman key exchange");
    acronyms.insert("DISA", "Defense Information Systems Agency");
    acronyms.insert("DKIM", "Domain Keys Identified Mail");
    acronyms.insert("DLL", "Dynamic-link Library");
    acronyms.insert("DLP", "Data Loss Prevention");
    acronyms.insert("DMARC", "Domain-based Message Authentication, Reporting & Conformance");
    acronyms.insert("DMA", "Direct Memory Access");
    acronyms.insert("DMZ", "Demilitarized Zone");
    acronyms.insert("DM", "Direct Message");
    acronyms.insert("DNS", "Deferred Net Settlement (banking)");
    acronyms.insert("DNS", "Domain Name System");
    acronyms.insert("DN", "Distinguished Name (LDAP)");
    acronyms.insert("DOB", "Date of Birth");
    acronyms.insert("DOM", "Document Object Model");
    acronyms.insert("DoS", "Denial of Service");
    acronyms.insert("DPAPI", "Data Protection API");
    acronyms.insert("DPA", "Data Processing Agreement");
    acronyms.insert("DPA", "Data Protection Act (UK law)");
    acronyms.insert("DPIA", "Data Protection Impact Assessment");
    acronyms.insert("DPP", "Data and Privacy Protection");
    acronyms.insert("DRAC", "Dell Remote Access Control");
    acronyms.insert("DRI", "Disaster Recovery Institute");
    acronyms.insert("DRM", "Digital Rights Management");
    acronyms.insert("DRP", "Disaster Recovery Planning");
    acronyms.insert("DR", "Disaster Recovery");
    acronyms.insert("DSA", "Digital Signature Algorithm");
    acronyms.insert("DSCI", "Data Security Council of India");
    acronyms.insert("DTP", "Dynamic Trunking Protocol (Cisco)");
    acronyms.insert("EBS", "Amazon Elastic Block Store");
    acronyms.insert("eCDFP", "eLearnSecurity Certified Digital Forensics Professional");
    acronyms.insert("ECES", "EC Council Certified Encryption Specialist");
    acronyms.insert("ECIH", "EC Council Certified Incident Handler");
    acronyms.insert("eCIR", "eLearnSecurity Certified Incident Responder");
    acronyms.insert("eCMAP", "eLearnSecurity Certified Malware Analysis Professional");
    acronyms.insert("eCPPT", "eLearnSecurity Certified Professional Penetration Tester");
    acronyms.insert("eCPTX", "eLearnSecurity Certified Penetration Tester eXtreme");
    acronyms.insert("eCRE", "eLearnSecurity Certified Reverse Engineer");
    acronyms.insert("ECSA", "EC Council Certified Security Analyst");
    acronyms.insert("ECSS", "EC Council Certified Security Specialist");
    acronyms.insert("eCTHP", "eLearnSecurity Certified Threat Hunting Professional");
    acronyms.insert("eCXD", "eLearnSecurity Certified eXploit Developer");
    acronyms.insert("EDRP", "EC Council Disaster Recovery Professional");
    acronyms.insert("EDR", "Endpoint Detection and Response");
    acronyms.insert("EEHF", "EXIN Ethical Hacking Foundation");
    acronyms.insert("EEXIN ISM", "EXIN Information Security Management Expert");
    acronyms.insert("EFF", "Electronic Frontier Foundation");
    acronyms.insert("EF", "Exposure Factor");
    acronyms.insert("EICAR", "Antivirus test file");
    acronyms.insert("EIGRP", "Enhanced Interior Gateway Routing Protocol");
    acronyms.insert("EISM", "EC Council Information Security Manager");
    acronyms.insert("EITCA/IS", "EITCA/IS Information Security Certificate");
    acronyms.insert("eJPT", "eLearnSecurity Junior Penetration Tester");
    acronyms.insert("ELF", "Executable and Linkable Format");
    acronyms.insert("EL", "Engagement Letter");
    acronyms.insert("eMAPT", "eLearnSecurity Mobile Application Penetration Tester");
    acronyms.insert("EMR", "Electromagnetic Radiation");
    acronyms.insert("EnCE", "OpenText EnCase Certified Examiner");
    acronyms.insert("eNDP", "eLearnSecurity Network Defense Professional");
    acronyms.insert("EOL", "End of Life");
    acronyms.insert("EOP", "Elevation/Escalation of Privilege");
    acronyms.insert("EOR", "Employer of Record");
    acronyms.insert("EPDPE", "EXIN Privacy and Data Protection Essentials");
    acronyms.insert("EPDPF", "EXIN Privacy and Data Protection Foundation");
    acronyms.insert("EPDPP", "EXIN Privacy and Data Protection Practitioner");
    acronyms.insert("EPT", "External Penetration Testing");
    acronyms.insert("ERP", "Enterprise Resource Planning");
    acronyms.insert("ES", "Enterprise Security");
    acronyms.insert("ETA", "Evil Twin Attack (Wi-Fi)");
    acronyms.insert("EVP", "Executive Vice President");
    acronyms.insert("eWDP", "eLearnSecurity Web Defense Professional");
    acronyms.insert("eWPTX", "eLearnSecurity Web Application Penetration Tester eXtreme");
    acronyms.insert("eWPT", "eLearnSecurity Web Application Penetration Tester");
    acronyms.insert("EXIN CIT", "EXIN Cyber & IT Security");
    acronyms.insert("EXIN PCA", "EXIN Professional Cloud Administrator");
    acronyms.insert("EXIN PCSA", "EXIN Professional Cloud Solution Architect");
    acronyms.insert("EXIN PCSerM", "EXIN Professional Cloud Service Manager");
    acronyms.insert("EXIN PCSM", "EXIN Professional Cloud Security Manager");
    acronyms.insert("F5 CA", "F5 Big-IP Certified Administrator");
    acronyms.insert("F5 CSE Sec", "F5 Big-IP Certified Solution Expert - Security");
    acronyms.insert("F5 CTS APM", "F5 Big-IP Certified Technical Specialist - Access Policy Manager");
    acronyms.insert("F5 CTS DNS", "F5 Big-IP Certified Technical Specialist - Domain Name Services");
    acronyms.insert("FDE", "Full Disk Encryption");
    acronyms.insert("FERPA", "Family Educational Rights and Privacy Act");
    acronyms.insert("FEXIN", "EXIN Information Security Foundation");
    acronyms.insert("FIM", "File Integrity Monitoring");
    acronyms.insert("FQDN", "Fully Qualified Domain Name");
    acronyms.insert("FTC", "Full Time Contract");
    acronyms.insert("FTE", "Full Time Employee");
    acronyms.insert("FTP", "File Transfer Protocol");
    acronyms.insert("FUD", "Fear, Uncertainty and Doubt");
    acronyms.insert("FW", "Firewall");
    acronyms.insert("FYI", "For Your Information");
    acronyms.insert("FYSA", "For Your Situational Awareness");
    acronyms.insert("GAQM", "Global Association for Quality Management");
    acronyms.insert("GASF", "GIAC Advanced Smartphone Forensics");
    acronyms.insert("GAWN", "GIAC Assessing Wireless Networks");
    acronyms.insert("GBFA", "GIAC Battlefield Forensics and Acquisition");
    acronyms.insert("GCCC", "GIAC Critical Controls Certification");
    acronyms.insert("GCDA", "GIAC Certified Detection Analyst");
    acronyms.insert("GCED", "GIAC Certified Enterprise Defender");
    acronyms.insert("GCFA", "GIAC Certified Forensic Analyst");
    acronyms.insert("GCFE", "GIAC Certified Forensics Examiner");
    acronyms.insert("GCIA", "GIAC Certified Intrusion Analyst");
    acronyms.insert("GCIH", "GIAC Certified Incident Handler");
    acronyms.insert("GCIP", "GIAC Critical Infrastructure Protection");
    acronyms.insert("GCPEH", "GAQM Certified Professional Ethical Hacker");
    acronyms.insert("GCPM", "GIAC Certified Project Manager");
    acronyms.insert("GCPT", "GAQM Certified Penetration Tester");
    acronyms.insert("GCSA", "GIAC Cloud Security Automation");
    acronyms.insert("GCTI", "GIAC Cyber Threat Intelligence");
    acronyms.insert("GCWN", "GIAC Certified Windows Security Administrator");
    acronyms.insert("GC", "Garbage Collection");
    acronyms.insert("GDAT", "GIAC Defending Advanced Threats");
    acronyms.insert("GDPR", "General Data Protection Regulation");
    acronyms.insert("GDSA", "GIAC Defensible Security Architecture");
    acronyms.insert("GEOINT", "Geospatial Intelligence");
    acronyms.insert("GEVA", "GIAC Enterprise Vulnerability Assessor");
    acronyms.insert("GIAC", "Global Information Assurance Certification");
    acronyms.insert("GICSP", "GIAC Global Industrial Security Professional");
    acronyms.insert("GISF", "GIAC Information Security Fundamentals");
    acronyms.insert("GISP", "GIAC Information Security Professional");
    acronyms.insert("GLEG", "GIAC Law of Data Security & Investigations");
    acronyms.insert("GMOB", "GIAC Mobile Device Security Analyst");
    acronyms.insert("GMON", "GIAC Continuous Monitoring");
    acronyms.insert("GNFA", "GIAC Network Forensic Analyst");
    acronyms.insert("Google ACE", "Google Associate Cloud Engineer");
    acronyms.insert("Google PCSA", "Google Professional Cloud Architect");
    acronyms.insert("Google PCSE", "Google Professional Cloud Security Engineer");
    acronyms.insert("GOSI", "GIAC Open Source Intelligence");
    acronyms.insert("GPEN", "GIAC Certified Penetration Tester");
    acronyms.insert("GPG", "GNU Privacy Guard");
    acronyms.insert("GPO", "Group Policy Object");
    acronyms.insert("GPPA", "GIAC Certified Perimeter Protection Analyst");
    acronyms.insert("GPP", "Group Policy Preferences (Active Directory)");
    acronyms.insert("GPYC", "GIAC Python Coder");
    acronyms.insert("GRC", "Governance, Risk and Compliance");
    acronyms.insert("GREM", "GIAC Reverse Engineering Malware");
    acronyms.insert("GRE", "Generic Routing Encapsulation");
    acronyms.insert("GRID", "GIAC Response and Industrial Defense");
    acronyms.insert("GSEC", "GIAC Security Essentials Certification");
    acronyms.insert( "GSE",	"GIAC Security Expert");
    acronyms.insert("GSLC", "GIAC Security Leadership Certification");
    acronyms.insert("GSM", "Global System for Mobile (communications)");
    acronyms.insert("GSNA", "GIAC Systems and Network Auditor");
    acronyms.insert("GSSP", "GIAC Secure Software Programmer JAVA or .NET");
    acronyms.insert("GSTRT", "GIAC Strategic Planning, Policy and Leadership");
    acronyms.insert("GUID", "Globally Unique Identifier");
    acronyms.insert("GUI", "Graphical User Interface");
    acronyms.insert("GWAPT", "GIAC Web Application Penetration Tester");
    acronyms.insert("GWEB", "GIAC Certified Web Application Defender");
    acronyms.insert("GWT", "Google Web Toolkit");
    acronyms.insert("GXPN", "GIAC Exploit Researcher and Advanced Penetration Tester");
    acronyms.insert("HIDS", "Host IDS (Intrusion Detection System)");
    acronyms.insert("HIPAA", "Health Insurance Portability Accountability Act");
    acronyms.insert("HIPS", "Host IPS (Intrusion Prevention System)");
    acronyms.insert("HKCC", "HKEY_CURRENT_CONFIG Windows registry hive");
    acronyms.insert("HKCR", "HKEY_CLASSES_ROOT Windows registry hive");
    acronyms.insert("HKCU", "HKEY_CURRENT_USER Windows registry hive");
    acronyms.insert("HKLM", "HKEY_LOCAL_MACHINE Windows registry hive");
    acronyms.insert("HKU", "HKEY_USERS Windows registry hive");
    acronyms.insert("HMAC", "Hash-based Message Authentication Code.");
    acronyms.insert("HOF", "Hall of Fame");
    acronyms.insert("HPP", "HTTP Parameter Pollution");
    acronyms.insert("HSTS", "HTTP Strict Transport Security");
    acronyms.insert("I2P", "Invisible Internet Project");
    acronyms.insert("IaaS", "Infrastructure as a Service");
    acronyms.insert("IACIS", "International Association of Computer Investigative Specialists");
    acronyms.insert("IACRB", "Information Assurance Certification Review Board");
    acronyms.insert("IAM", "Identity Access Management");
    acronyms.insert("IANAL", "I am not a lawyer");
    acronyms.insert("IAPP", "International Association of Privacy Professionals");
    acronyms.insert("IAR", "Information Asset Register");
    acronyms.insert("IAST", "Interactive Application Security Testing");
    acronyms.insert("IAVA", "Information Assurance Vulnerability Alert");
    acronyms.insert("IAVM", "Information Assurance Vulnerability Management");
    acronyms.insert("IBITGQ", "International Board for IT Governance Qualifications");
    acronyms.insert("ICE", "Intrusion Countermeasures Electronics");
    acronyms.insert("ICMP", "Internet Control Message Protocol");
    acronyms.insert("ICS", "Incident Command System");
    acronyms.insert("IDEs", "Integrated Development Environments");
    acronyms.insert("IDM", "Identity Management");
    acronyms.insert("IDOR", "Insecure Direct Object Reference");
    acronyms.insert("IDS", "Intrusion Detection System");
    acronyms.insert("ID", "Information Disclosure");
    acronyms.insert("IEC", "International Electrotechnical Commission");
    acronyms.insert("IEEE", "Institute of Electrical and Electronics Engineers");
    acronyms.insert("IETF", "Internet Engineering Task Force");
    acronyms.insert("IG", "Information Governance");
    acronyms.insert("IIA CIA", "Institute of Internal Auditors Certified Internal Auditor");
    acronyms.insert("IIA", "Institute of Internal Auditors");
    acronyms.insert("IIBA CCA", "IIBA Certification in Cybersecurity Analysis");
    acronyms.insert("IIBA", "International Institute of Business Analysis");
    acronyms.insert("IIoT", "Industrial Internet of Things");
    acronyms.insert("IIRC", "If I recall correctly");
    acronyms.insert("IKE", "Internet Key Exchange");
    acronyms.insert("iLO", "HP Integrated Lights Out");
    acronyms.insert("IMI", "Identity Management Institute");
    acronyms.insert("IMMA", "Isolate, Minimize, Monitor, Active Defense (IR)");
    acronyms.insert("IMPS", "Immediate Payment Service (banking)");
    acronyms.insert("IM", "Instant Messaging");
    acronyms.insert("IOC", "Indicator of Compromise");
    acronyms.insert("IoT", "Internet of Things");
    acronyms.insert("IPMI", "Intelligent Platform Management Interface");
    acronyms.insert("IPP", "Internet Printing Protocol");
    acronyms.insert("IPsec", "Internet Protocol Security");
    acronyms.insert("IPSec", "Internet Protocol Security");
    acronyms.insert("IPS", "Intrusion Prevention System");
    acronyms.insert("IPT", "Internal Penetration Testing");
    acronyms.insert("IP", "Intellectual Property");
    acronyms.insert("IP", "Internet Protocol");
    acronyms.insert("IRC", "Internet Relay Chat");
    acronyms.insert("IRL", "In real life");
    acronyms.insert("IRM", "Information Rights Management");
    acronyms.insert("IRP", "Incident Response Plan or Policy");
    acronyms.insert("IR", "Incident Response");
    acronyms.insert("ISACA", "Information Systems Audit and Control Association");
    acronyms.insert("ISAC", "Information Sharing and Analysis Center");
    acronyms.insert("ISAKMP", "Internet Security Association Key Management Protocol");
    acronyms.insert("ISA CE", "ISA Cybersecurity Expert");
    acronyms.insert("ISA CFS", "ISA Certified Fundamentals Specialist");
    acronyms.insert("ISA CRAS", "ISA Certified Risk Assessment Specialist");
    acronyms.insert("ISA", "International Society of Automation");
    acronyms.insert("ISECOM", "Institute for Security and Open Methodologies");
    acronyms.insert("ISMS", "Information Security Management System");
    acronyms.insert("ISM", "Information Security Manual");
    acronyms.insert("ISO", "Information System Owner (in RMF - Risk Management Framework)");
    acronyms.insert("ISO", "International Organization for Standardization");
    acronyms.insert("ISP", "Internet Service Provider");
    acronyms.insert("ISSAF", "Information Systems Security Assessment Framework");
    acronyms.insert("ITIL Fdn", "ITIL Foundation");
    acronyms.insert("ITIL Master", "ITIL Master");
    acronyms.insert("ITIL MP", "ITIL Managing Professional");
    acronyms.insert("ITIL SL", "ITIL Strategic Leader");
    acronyms.insert("ITIL", "Information Technology Infrastructure Library");
    acronyms.insert("IT", "Information Technology");
    acronyms.insert("I&C", "Instrumentation and Control");
    acronyms.insert("JCE", "Java Cryptography Extension");
    acronyms.insert("JMX", "Java Management Extensions");
    acronyms.insert("JNCIA Sec", "Juniper Networks Certified Internet Associate, Security");
    acronyms.insert("JNCIE Sec", "Juniper Networks Certified Internet Expert, Security");
    acronyms.insert("JNCIP Sec", "Juniper Networks Certified Internet Professional, Security");
    acronyms.insert("JNCIS Sec", "Juniper Networks Certified Internet Specialist, Security");
    acronyms.insert("JPEG", "Joint Photographic Experts Group");
    acronyms.insert("JSON", "JavaScript Object Notation");
    acronyms.insert("JSP", "Jakarta Server Pages");
    acronyms.insert("JSP", "Java Servlet Pages");
    acronyms.insert("JS", "JavaScript");
    acronyms.insert("JVM", "Java Virtual Machine");
    acronyms.insert("JWT", "JSON Web Token");
    acronyms.insert("K8S", "Kubernetes");
    acronyms.insert("KC", "Kill Chain");
    acronyms.insert("KLCP", "Kali Linux Certified Professional");
    acronyms.insert("KMaaS", "Key Management as a Service");
    acronyms.insert("KMS", "Key Management Service");
    acronyms.insert("LAMP", "Linux, Apache, MySQL, and PHP");
    acronyms.insert("LAN", "Local Area Network");
    acronyms.insert("LDAP", "Lightweight Directory Access Protocol");
    acronyms.insert("LE", "Let's Encrypt");
    acronyms.insert("LFCA", "Linux Foundation Certified IT Associate");
    acronyms.insert("LFCE", "Linux Foundation Certified Engineer");
    acronyms.insert("LFCS", "Linux Foundation Certified System Administrator");
    acronyms.insert("LFI", "Local File Inclusion");
    acronyms.insert("LKM", "Loadable Kernel Modules");
    acronyms.insert("LLMNR", "Link-Local Multicast Name Resolution protocol");
    acronyms.insert("LM", "LAN Manager (Windows)");
    acronyms.insert("LOIC", "Low Orbit Ion Cannon");
    acronyms.insert("LPA", "Least Privilege Access");
    acronyms.insert("LPE", "Local Privilege Escalation");
    acronyms.insert("LPIC-1", "Linux Professional Institute Certified: Linux Administrator");
    acronyms.insert("LPIC-2", "Linux Professional Institute Certified: Linux Engineer");
    acronyms.insert("LPIC-3", "Linux Professional Institute Certified: 303 Security");
    acronyms.insert("LPT", "EC Council Licensed Penetration Tester");
    acronyms.insert("LSASS", "Local Security Authority Subsystem Service");
    acronyms.insert("LTE", "Long-Term Evolution");
    acronyms.insert("LTS", "Long-Term Support");
    acronyms.insert("M365 EAE", "Microsoft 365 Certified Enterprise Administrator Expert");
    acronyms.insert("MAC", "Mandatory Access Control");
    acronyms.insert("MAC", "Media Access Control (MAC address)");
    acronyms.insert("MAC", "Message Authentication Code");
    acronyms.insert("MAC", "Milestone Acceptance Certificate");
    acronyms.insert("MD5", "Message Digest 5 (hash)");
    acronyms.insert("MDR", "Managed Detection and Response");
    acronyms.insert("MFA", "Multi-factor Authentication");
    acronyms.insert("MIME", "Multipurpose Internet Mail Extensions");
    acronyms.insert("MISP", "Malware Information Sharing Platform");
    acronyms.insert("MitM", "Man-in-the-Middle");
    acronyms.insert("MMC", "Microsoft Management Console");
    acronyms.insert("MOTD", "Message of the day banner");
    acronyms.insert("MPLS", "Multi-Protocol Label Switching");
    acronyms.insert("MQ", "Message Queue");
    acronyms.insert("MRA", "Mobile and Remote Access");
    acronyms.insert("MSA", "Master Service Agreement");
    acronyms.insert("MSCT", "Microsoft Security Compliance Toolkit");
    acronyms.insert("MSSP", "Managed Security Services Provider");
    acronyms.insert("MS", "Member Server (Active Directory)");
    acronyms.insert("MS", "Microsoft");
    acronyms.insert("MTA", "Microsoft Technology Associate");
    acronyms.insert("MVP", "Minimum Viable Product (the smallest, simplest thing that meets the criteria)");
    acronyms.insert("NAC", "Network Access Control");
    acronyms.insert("NAT", "Network Address Translation");
    acronyms.insert("NBNS", "NetBIOS Name Service");
    acronyms.insert("NCSC CCPLP", "NCSC Certified Cybersecurity Professional - Lead Practitioner");
    acronyms.insert("NCSC CCPP", "NCSC Certified Cybersecurity Professional - Practitioner");
    acronyms.insert("NCSC CCPSP", "NCSC Certified Cybersecurity Professional - Senior Practitioner");
    acronyms.insert("NCSC", "National Cyber Security Centre");
    acronyms.insert("NCS", "National Cybersecurity Strategy");
    acronyms.insert("NDA", "Non-disclosure agreement");
    acronyms.insert("NEFT", "National Electronic Funds Transfer (banking)");
    acronyms.insert("Net+", "CompTIA Network+");
    acronyms.insert("NFS", "Network File System");
    acronyms.insert("NGFW", "Next Generation Firewall");
    acronyms.insert("NIDS", "Network IDS (Intrusion Detection System)");
    acronyms.insert("NIPS", "Network IPS (Intrusion Prevention System)");
    acronyms.insert("NIST", "National Institute of Science & Technology");
    acronyms.insert("NLA", "Network Level Authentication");
    acronyms.insert("NOC", "Network Operations Centre");
    acronyms.insert("NOP", "No Operation");
    acronyms.insert("NPE", "Null Pointer Exception");
    acronyms.insert("NSE 4", "NSE 4 - FortiNET Network Security Professional");
    acronyms.insert("NSE 7", "NSE 7 - FortiNET Network Security Architect");
    acronyms.insert("NSE 8", "NSE 8 - Fortinet Network Security Expert");
    acronyms.insert("NTLM", "New Technology LAN Manager (Windows)");
    acronyms.insert("NVD", "National Vulnerability Database");
    acronyms.insert("OBOE", "Off-by-one Error");
    acronyms.insert("OCR", "Optical Character Recognition");
    acronyms.insert("OEM", "Original Equipment Manufacturer");
    acronyms.insert("OOB", "Out-of-band");
    acronyms.insert("OOP", "Object-oriented Programming");
    acronyms.insert("OPSA", "ISECOM OSSTMM Professional Security Analyst");
    acronyms.insert("OPSEC", "Operations Security");
    acronyms.insert("OPSE", "ISECOM OSSTMM Professional Security Expert");
    acronyms.insert("OPST", "ISECOM OSSTMM Professional Security Tester");
    acronyms.insert("OSCE", "Offensive Security Certified Expert");
    acronyms.insert("OSCP", "Offensive Security Certified Professional");
    acronyms.insert("OSEE", "Offensive Security Exploitation Expert");
    acronyms.insert("OSEP", "Offensive Security Experienced Penetration Tester");
    acronyms.insert("OSGI", "Open Services Gateway Initiative");
    acronyms.insert("OSINT", "Open Source Intelligence");
    acronyms.insert("OSPF", "Open Shortest Path First");
    acronyms.insert("OSSTMM", "Open Source Security Testing Methodology Manual");
    acronyms.insert("OSWE", "Offensive Security Web Expert");
    acronyms.insert("OSWP", "Offensive Security Wireless Professional");
    acronyms.insert("OTA", "Over-the-air programming");
    acronyms.insert("OTP", "One-time Password");
    acronyms.insert("OTX", "Open Threat Exchange");
    acronyms.insert("OT", "Operational Technology");
    acronyms.insert("OWASP", "Open Web Application Security Project");
    acronyms.insert("OWA", "Outlook Web Access");
    acronyms.insert("OWSE", "ISECOM OSSTMM Wireless Security Expert");
    acronyms.insert("P2P", "Peer to Peer");
    acronyms.insert("PaaS", "Platform as a service");
    acronyms.insert("PACES", "Pentester Academy Certified Enterprise Security Specialist");
    acronyms.insert("PAM", "Post-Accident Monitoring");
    acronyms.insert("PAN", "Personal Area Network");
    acronyms.insert("PAN", "Primary Account Number");
    acronyms.insert("PASTA", "Process for Attack Simulation and Threat Analysis");
    acronyms.insert("PA CRTE", "Pentester Academy Certified Red Teaming Expert");
    acronyms.insert("PA CRTP", "Pentester Academy Certified Red Team Professional");
    acronyms.insert("PCAP", "Packet Capture");
    acronyms.insert("PCCSA", "Palo Alto Networks Certified Cybersecurity Associate");
    acronyms.insert("PCIDSS", "Payment Card Industry Data Security Standards");
    acronyms.insert("PCI", "Payment Card Industry");
    acronyms.insert("PCNSA", "Palo Alto Networks Certified Network Security Administrator");
    acronyms.insert("PCNSE", "Palo Alto Networks Certified Network Security Engineer");
    acronyms.insert("PCRE", "Perl-compatible Regular Expressions");
    acronyms.insert("PDF", "Portable Document Format");
    acronyms.insert("PEBCAK", "Problem Exists Between Chair and Keyboard");
    acronyms.insert("PEBKAC", "Problem Exists Between Keyboard And Chair.");
    acronyms.insert("PEB", "Process Environment Block");
    acronyms.insert("Pentest+", "CompTIA Pentest+");
    acronyms.insert("PERSEC", "Personal Security (military)");
    acronyms.insert("PEXIN ISM", "EXIN Information Security Management Professional");
    acronyms.insert("PE", "Portable Executable (Windows executable)");
    acronyms.insert("PE", "Privilege Escalation");
    acronyms.insert("PFS", "Perfect Forward Secrecy");
    acronyms.insert("PGP", "Pretty Good Privacy");
    acronyms.insert("PHI", "Protected Health Information");
    acronyms.insert("PHR", "Personal Health Record");
    acronyms.insert("PIC", "Position Independent Code");
    acronyms.insert("PID", "Process Identifier");
    acronyms.insert("PII", "Personally Identifiable Information");
    acronyms.insert("PIN", "Personal Identification Number");
    acronyms.insert("PKI", "Public Key Infrastructure");
    acronyms.insert("PLC", "Programmable Logic Controller");
    acronyms.insert("PLC", "Programmable Logic Controllers");
    acronyms.insert("PLD", "Payload");
    acronyms.insert("PMI", "Project Management Institute");
    acronyms.insert("PMP", "Project Management Professional certification");
    acronyms.insert("PM", "Product Manager");
    acronyms.insert("PM", "Program Manager");
    acronyms.insert("PNG", "Portable Network Graphics");
    acronyms.insert("POA&M", "Plan of Action & Mitigation");
    acronyms.insert("PoC", "Proof of Concept");
    acronyms.insert("PoE", "Power over Ethernet");
    acronyms.insert("POP", "Post Office Protocol");
    acronyms.insert("POP", "Procedure-oriented Programming");
    acronyms.insert("PO", "Purchase Order");
    acronyms.insert("PPPoEoA", "PPPoE over ATM");
    acronyms.insert("PPPoE", "Point-to-Point Protocol over Ethernet");
    acronyms.insert("PPP", "Point-to-Point Protocol");
    acronyms.insert("PPP", "Public Private Partnership");
    acronyms.insert("PPS", "Plant Protection System");
    acronyms.insert("PRNG", "Pseudo-Random Number Generator");
    acronyms.insert("PSH", "Powershell");
    acronyms.insert("PSK", "Pre-shared Key");
    acronyms.insert("PTES", "Penetration Testing Execution Standard");
    acronyms.insert("PTO", "Personal Time Off");
    acronyms.insert("PTRF", "Penetration Test Request Form");
    acronyms.insert("PTR", "DNS pointer record (hostname -> IP)");
    acronyms.insert("PTR", "Penetration Test Request");
    acronyms.insert("PT", "Penetration Test");
    acronyms.insert("QR", "Quick Response code");
    acronyms.insert("QSA", "Quality Security Assessor");
    acronyms.insert("RASP", "Runtime Application Self-Protection");
    acronyms.insert("RAT", "Remote Access Tool");
    acronyms.insert("RAT", "Remote Administration Tool");
    acronyms.insert("RBAC", "Role Based Access Control");
    acronyms.insert("RBA", "Risk-based Assessment");
    acronyms.insert("RCA", "Root Cause Analysis");
    acronyms.insert("RCE", "Remote Code Execution");
    acronyms.insert("RCP", "Remote Copy");
    acronyms.insert("RDP", "Remote Desktop Protocol");
    acronyms.insert("REST", "Representational State Transfer (web services)");
    acronyms.insert("REXEC", "Remote Execute");
    acronyms.insert("RE", "Reverse Engineering");
    acronyms.insert("RFID", "Radio Frequency Identification (card)");
    acronyms.insert("RFI", "Remote File Inclusion");
    acronyms.insert("RFI", "Request For Information");
    acronyms.insert("RFP", "Request For Proposal");
    acronyms.insert("RFQ", "Request for Quotation");
    acronyms.insert("RHCA", "Red Hat Certified Architect");
    acronyms.insert("RHCE", "Red Hat Certified Engineer");
    acronyms.insert("RHCSA", "Red Hat Certified System Administrator");
    acronyms.insert("RMF", "Risk Management Framework");
    acronyms.insert("RMI", "Remote Method Invocation");
    acronyms.insert("RM", "Records Management");
    acronyms.insert("RoE", "Rules of Engagement");
    acronyms.insert("ROM", "Read-Only Medium");
    acronyms.insert("ROM", "Read-Only Memory");
    acronyms.insert("ROPA", "Record of Processing Activity (GDPR article 30)");
    acronyms.insert("ROP", "Return Oriented Programming");
    acronyms.insert("RPC", "Remote Procedure Call");
    acronyms.insert("RPO", "Recovery Point Objective");
    acronyms.insert("RSA", "Rivest-Shamir-Adleman (encryption)");
    acronyms.insert("RSH", "Remote Shell");
    acronyms.insert("RTFM", "Read The Fucking Manual");
    acronyms.insert("RTGS", "Real-Time Gross Settlement (banking)");
    acronyms.insert("RTO", "Recovery Time Objective");
    acronyms.insert("RTP", "Real-time Transport Protocol");
    acronyms.insert("SaaS", "Security as a Service");
    acronyms.insert("SaaS", "Software as a Service");
    acronyms.insert("SABSA SCF", "SABSA Chartered Security Architect - Foundation Certificate");
    acronyms.insert("SABSA SCM", "SABSA Chartered Security Architect - Master Certificate");
    acronyms.insert("SABSA SCP", "SABSA Chartered Security Architect - Practitioner Certificate");
    acronyms.insert("SAML", "Security Assertion Markup Language");
    acronyms.insert("SANS", "SysAdmin Audit Network Security institute");
    acronyms.insert("SASL", "Simple Authentication and Security Layer");
    acronyms.insert("SAST", "Static Application Security Testing");
    acronyms.insert("SA", "Security Association (VPN)");
    acronyms.insert("SA", "Situational Awareness");
    acronyms.insert("SBC", "Session Border Controller");
    acronyms.insert("SBC", "Single Board Computer");
    acronyms.insert("SCADA", "Supervisory Control And Data Acquisition");
    acronyms.insert("SCA", "Software Composition Analysis");
    acronyms.insert("SCA", "SUSE Certified Administrator");
    acronyms.insert("SCCM", "System Center Configuration Manager");
    acronyms.insert("SCCs", "Standard Contractual Clauses");
    acronyms.insert("SCD", "Source Code Disclosure");
    acronyms.insert("SCE", "SUSE Certified Engineer");
    acronyms.insert("SDA", "Sensitive Digital Assets");
    acronyms.insert("SDK", "Software Development Kit");
    acronyms.insert("SDLC", "Software Development Lifecycle");
    acronyms.insert("SDN", "Software-defined Networking");
    acronyms.insert("SECaaS", "Security as a Service");
    acronyms.insert("SECO", "Security & Continuity Institute");
    acronyms.insert("SEH", "Structured Exception Handling");
    acronyms.insert("SFCCCC", "SalesForce Certified Community Cloud Consultant");
    acronyms.insert("SFCIAMD", "SalesForce Certified Identity and Access Management Designer");
    acronyms.insert("SFCTA", "Salesforce Certified Technical Architect");
    acronyms.insert("SFSA", "SalesForce System Architect");
    acronyms.insert("SHA", "Secure Hash Algorithm");
    acronyms.insert("SID", "Security Identifier (Windows)");
    acronyms.insert("SIEM", "Security Information and Event Management");
    acronyms.insert("SIP", "Session Initiation Protocol");
    acronyms.insert("SIR", "Security Incident Response (plan)");
    acronyms.insert("SLAAC", "Stateless Address Autoconfiguration (attack)");
    acronyms.insert("SLA", "Service-level Agreement");
    acronyms.insert("SLD", "Second-level Domain");
    acronyms.insert("SLE", "Single Loss Expectancy");
    acronyms.insert("SMB", "Server Message Block");
    acronyms.insert("SME", "Subject Matter Expert");
    acronyms.insert("SMTP", "Simple Mail Transfer Protocol");
    acronyms.insert("SNMP", "Simple Network Management Protocol");
    acronyms.insert("SOAP", "Simple Object Access Protocol");
    acronyms.insert("SOAR", "Security Orchestration, Automation and Response");
    acronyms.insert("SOA", "Service-oriented Architecture");
    acronyms.insert("SOA", "Start of authority record (DNS)");
    acronyms.insert("SOCaaS", "Security Operations Center as a Service");
    acronyms.insert("SOCKS", "Socket Secure protocol");
    acronyms.insert("SOCMINT", "Social Media Intelligence");
    acronyms.insert("SOC", "Security Operations Center");
    acronyms.insert("SOC", "System On a Chip");
    acronyms.insert("SOHO", "Small Office, Home Office");
    acronyms.insert("SOP", "Same-origin Policy");
    acronyms.insert("SOP", "Standard Operating Procedure");
    acronyms.insert("SOW", "Statement of Work");
    acronyms.insert("SPF", "Sender Policy Framework");
    acronyms.insert("SPI", "Security Parameter Index");
    acronyms.insert("Splunk ECSA", "Splunk Enterprise Security Certified Administrator");
    acronyms.insert("SPN", "Service Principal Name");
    acronyms.insert("SQLi", "SQL Injection");
    acronyms.insert("SRE", "Site Reliability Engineering");
    acronyms.insert("SRI", "Security Risk Intelligence");
    acronyms.insert("SRP", "Software Restriction Policies (Windows)");
    acronyms.insert("SSCP", "(ISC)2 Systems Security Certified Practitioner");
    acronyms.insert("SSDLC", "Secure Software Development Lifecycle");
    acronyms.insert("SSE", "Server Side Encryption");
    acronyms.insert("SSH", "Secure Shell");
    acronyms.insert("SSID", "Service Set Identifier");
    acronyms.insert("SSI", "Server Side Includes");
    acronyms.insert("SSL", "Secure Sockets Layer");
    acronyms.insert("SSN", "Social Security number");
    acronyms.insert("SSO", "Single Sign-on");
    acronyms.insert("SSP", "Security Support Provider");
    acronyms.insert("SSRF", "Server-side Request Forgery");
    acronyms.insert("STEM", "Science, Technology, Engineering, and Math");
    acronyms.insert("STIG", "Security Technical Implementation Guides");
    acronyms.insert("STIX", "Structured Threat Information Expression");
    acronyms.insert("STP", "Spanning Tree Protocol");
    acronyms.insert("STS", "Security Token Service");
    acronyms.insert("STUN", "Session Traversal Utilities for NAT");
    acronyms.insert("SVP", "Senior Vice President");
    acronyms.insert("SWRE", "Software Reverse Engineering");
    acronyms.insert("S-CEHL", "SECO Certified Ethical Hacker Leader");
    acronyms.insert("S-CISO", "SECO Certified Information Security Officer");
    acronyms.insert("S-EHE", "SECO Ethical Hacker Expert");
    acronyms.insert("S-EHF", "SECO Ethical Hacking Foundation");
    acronyms.insert("S-EHP", "SECO Ethical Hacking Practitioner");
    acronyms.insert("S-ISF", "SECO Information Security Foundation");
    acronyms.insert("S-ISME", "SECO Information Security Management Expert");
    acronyms.insert("S-ISP", "SECO Information Security Practitioner");
    acronyms.insert("S-SPF", "SECO Secure Programming Foundation");
    acronyms.insert("TBD", "To Be Discussed");
    acronyms.insert("TBD", "To Be Done");
    acronyms.insert("TCO", "Total Cost of Ownership");
    acronyms.insert("TCP", "Transmission Control Protocol");
    acronyms.insert("TEB", "Thread Environment Block");
    acronyms.insert("TGT", "Ticket Granting Ticket (Kerberos)");
    acronyms.insert("TI", "Threat Intelligence");
    acronyms.insert("TKIP", "Temporal Key Integrity Protocol");
    acronyms.insert("TLDR", "Too long, didn't read");
    acronyms.insert("TLD", "Top-level Domain");
    acronyms.insert("TLS", "Transport Layer Security");
    acronyms.insert("TOCTOU", "Time-of-check to time-of-use (race condition)");
    acronyms.insert("ToE", "Target of Evaluation");
    acronyms.insert("TOGAF Fdn", "OpenGroup TOGAF Certified");
    acronyms.insert("TOGAF", "The Open Group Architecture Framework");
    acronyms.insert("TOR", "The Onion Router");
    acronyms.insert("TOTP", "Time-based One-time Password");
    acronyms.insert("TPB", "The Pirate Bay");
    acronyms.insert("TPM", "Technical Product Manager");
    acronyms.insert("TPM", "Technical Program Manager");
    acronyms.insert("TPM", "Trusted Platform Module");
    acronyms.insert("TPoC", "Technical Point of Contact");
    acronyms.insert("TTD", "Time to Detection");
    acronyms.insert("TTL", "Time to live (IP, DNS, HTTP protocols)");
    acronyms.insert("TTP", "Tactics, Techniques, and Procedures");
    acronyms.insert("TUV Auditor", "TUV Rheinland IT Security Auditor (GERMAN)");
    acronyms.insert("TUV COTCP", "TUV Rheinland Certified Operational Technology Cybersecurity Professional (GERMAN)");
    acronyms.insert("TUV CyAware", "TUV Rheinland Cybersecurity Awareness (GERMAN)");
    acronyms.insert("TUV CySec", "TUV Rheinland Cybersecurity Specialist (GERMAN)");
    acronyms.insert("TUV ITSM", "TUV IT Security Manager (GERMAN)");
    acronyms.insert("TUV MSA", "TUV Rheinland Mobile Security Analyst (GERMAN)");
    acronyms.insert("UAC", "User Account Control");
    acronyms.insert("UAT", "User Acceptance Testing");
    acronyms.insert("UBA", "User Behaviour Analytics");
    acronyms.insert("UC", "Unified Communications");
    acronyms.insert("UC", "Unintended Consequences");
    acronyms.insert("UDP", "User Datagram Protocol");
    acronyms.insert("UEBA", "User and Entity Behaviour Analytics");
    acronyms.insert("UPI", "Unified Payments Interface (banking)");
    acronyms.insert("UPS", "Uninterruptible Power Supply");
    acronyms.insert("URI", "Uniform Resource Identifier");
    acronyms.insert("URL", "Uniform Resource Locator");
    acronyms.insert("URN", "Uniform / Universal Resource Name");
    acronyms.insert("UTMS", "Universal Mobile Telecommunications Service");
    acronyms.insert("UUID", "Universally Unique Identifier");
    acronyms.insert("VAPT", "Vulnerability Assessment and Penetration Test");
    acronyms.insert("VA", "Vulnerability Assessment");
    acronyms.insert("VCDX DCV", "VMware Certified Design Expert in Datacenter Virtualization");
    acronyms.insert("VCIX DCV", "VMware Certified Implementation Expert in Datacenter Virtualization");
    acronyms.insert("VCIX NV", "VMware Certified Implementation Expert in Network Virtualization");
    acronyms.insert("VCP DCV", "VMware Certified Professional in Datacenter Virtualization");
    acronyms.insert("VCP NV", "VMware Certified Professional in Network Virtualization");
    acronyms.insert("VCS", "Cisco TelePresence Video Communication Server (SIP trunk)");
    acronyms.insert("VDI", "Virtual Desktop Infrastructure");
    acronyms.insert("VDP", "Vulnerability Disclosure Program");
    acronyms.insert("VLAN", "Virtual Local Area Network");
    acronyms.insert("VLOM", "Vulnerability Lifecycle Management");
    acronyms.insert("VMP", "Vulnerability Management Program");
    acronyms.insert("VM", "Virtual Machine");
    acronyms.insert("VM", "Vulnerability Management");
    acronyms.insert("VNC", "Virtual Network Computing");
    acronyms.insert("VoIP", "Voice over Internet Protocol");
    acronyms.insert("VPC", "Virtual Private Cloud");
    acronyms.insert("VPLS", "Virtual Private LAN Service");
    acronyms.insert("VPN", "Virtual Private Network");
    acronyms.insert("VPRN", "Virtual Private Routed Network");
    acronyms.insert("VPR", "Vulnerability Priority Rating");
    acronyms.insert("VPS", "Virtual Private Server");
    acronyms.insert("VP", "Vice President");
    acronyms.insert("VR", "Vulnerability Research");
    acronyms.insert("VSA", "Vendor Security Assessment");
    acronyms.insert("WAF", "Web Application Firewall");
    acronyms.insert("WAMP", "Windows, Apache, MySQL, and PHP");
    acronyms.insert("WAN", "Wide Area Network");
    acronyms.insert("WAPT", "Web Application Penetration Test");
    acronyms.insert("WAP", "Web Application Protection");
    acronyms.insert("WAP", "Wireless Access Point");
    acronyms.insert("WCE", "Windows Credentials Editor");
    acronyms.insert("WCNA", "Protocol Analysis Institute Wireshark Certified Network Analyst");
    acronyms.insert("WebDAV", "Web Distributed Authoring and Versioning");
    acronyms.insert("WEP", "Wired Equivalent Privacy");
    acronyms.insert("WIDS", "Wireless Intrusion Detection System");
    acronyms.insert("WIPS", "Wireless Intrusion Prevention System");
    acronyms.insert("WIP", "Work in Progress");
    acronyms.insert("WMI", "Windows Management Instrumentation");
    acronyms.insert("WPA", "Wi-Fi Protected Access");
    acronyms.insert("WUI", "Web User Interface");
    acronyms.insert("XHR", "XMLHttpRequest");
    acronyms.insert("XMPP", "Extensible Messaging and Presence Protocol");
    acronyms.insert("XOR", "Exclusive Or (encryption)");
    acronyms.insert("XSLT", "Extensible Stylesheet Language Transformations");
    acronyms.insert("XSL", "Extensible Stylesheet Language");
    acronyms.insert("XSRF", "Cross Site Request Forgery");
    acronyms.insert("XSS", "Cross Site Scripting");
    acronyms.insert("XXE", "XML External Entity");
    acronyms.insert("YARA", "Yet Another Recursive Acronym");
    acronyms.insert("Zach EAA", "Zachman Enterprise Architect Associate (Level 1)");
    acronyms.insert("Zach EAPro", "Zachman Enterprise Architect Professional (Level 3)");
    acronyms.insert("Zach EAP", "Zachman Enterprise Architect Practitioner (Level 2)");
    acronyms.insert("ZT", "Zero Trust");

    return acronyms;
}
